In [1]:
import numpy as np

In [2]:
M = np.array([[3, 8, 2], [4, 6, 5], [19, 21, 4]])       # Schlüsselmatrix M
print(M)

[[ 3  8  2]
 [ 4  6  5]
 [19 21  4]]


In [26]:
def Inverse(Matrix):           # Definition für inverse 3x3-Matrix
    
    det = (M[0,0]*M[1,1]*M[2,2]+M[0,1]*M[1,2]*M[2,0]+M[0,2]*M[1,0]*M[2,1])-(M[0,2]*M[1,1]*M[2,0]+M[0,0]*M[1,2]*M[2,1]+M[0,1]*M[1,0]*M[2,2])
    # Determinante von Matrix
    
    Adj = np.array([[(M[2,2]*M[1,1]-M[1,2]*M[2,1]), -1*(M[0,1]*M[2,2]-M[0,2]*M[2,1]), (M[1,2]*M[0,1]-M[0,2]*M[1,1])],
                    [-1*(M[1,0]*M[2,2]-M[1,2]*M[2,0]), (M[0,0]*M[2,2]-M[0,2]*M[2,0]), -1*(M[0,0]*M[1,2]-M[0,2]*M[1,0])],
                    [(M[1,0]*M[2,1]-M[1,1]*M[2,0]), -1*(M[0,0]*M[2,1]-M[0,1]*M[2,0]), (M[0,0]*M[1,1]-M[0,1]*M[1,0])]])
    # adjunkte Matrix 
    
    Minvers = ((1/det) * Adj)   # Formel für inverse Matrix
    
    
    return Minvers

In [27]:
I = Inverse(M)          # Inverse Matrix zu M

print(I)

[[-0.24620061  0.03039514  0.08510638]
 [ 0.24012158 -0.07902736 -0.0212766 ]
 [-0.09118541  0.27051672 -0.04255319]]


In [33]:
print(np.dot(M, I))   # Test M * I ergibt die Einheitsmatrix

[[  1.00000000e+00   0.00000000e+00  -1.38777878e-17]
 [  1.11022302e-16   1.00000000e+00   0.00000000e+00]
 [  2.77555756e-16   0.00000000e+00   1.00000000e+00]]


In [30]:
In = I % 26
print(In)

[[ 25.75379939   0.03039514   0.08510638]
 [  0.24012158  25.92097264  25.9787234 ]
 [ 25.90881459   0.27051672  25.95744681]]


In [34]:
Alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'    # Liste mit Alphabet
Lalphabet = list(Alphabet)

In [35]:
Eingabe = 'WHKPXLMMFQXAGUQ'
Leingabe= list(Eingabe)                          # Umwandlung des Eingabestrings zu Liste

In [36]:
L = []
for i in range(len(Leingabe)):                   # die Buchstaben der Eingabe werden durch den entsprechenden Index im Alphabet
    if Leingabe[i] in Lalphabet:                 # ersetzt und zu neuer Liste hinzugefügt
        L.append(Lalphabet.index(Leingabe[i]))
    
print(L)

[22, 7, 10, 15, 23, 11, 12, 12, 5, 16, 23, 0, 6, 20, 16]


In [38]:
v1 = [[22], [7], [10]]  # Vektoren mit den 'übersetzten' Buchstaben
v2 = [[15], [23], [11]]
v3 = [[12], [12], [5]]
v4 = [[16], [23], [0]]
v5 = [[6], [20], [16]]

In [41]:
print(np.dot(In, v1) % 26)  # Entschlüsselung mit inverser Matrix
print(np.dot(In, v2) % 26) 
print(np.dot(In, v3) % 26)
print(np.dot(In, v4) % 26)
print(np.dot(In, v5) % 26)

[[ 21.64741641]
 [  4.51671733]
 [ 25.46200608]]
[[ 23.94224924]
 [  1.55015198]
 [  4.38601824]]
[[ 23.83586626]
 [  1.82674772]
 [  1.93920973]]
[[ 22.75987842]
 [  2.02431611]
 [  4.76291793]]
[[  0.49240122]
 [ 25.51975684]
 [  4.18237082]]


In [42]:
print(Lalphabet[21],Lalphabet[4],Lalphabet[25],Lalphabet[23],Lalphabet[1],Lalphabet[4],Lalphabet[23],Lalphabet[1],
     Lalphabet[1],Lalphabet[22],Lalphabet[2],Lalphabet[4],Lalphabet[0],Lalphabet[25],Lalphabet[4])

# Übersetzung der Zahlen in Buchstaben (Ziffern vor dem Komma)

V E Z X B E X B B W C E A Z E


In [43]:
print(Lalphabet[22],Lalphabet[5],Lalphabet[25],Lalphabet[24],Lalphabet[2],Lalphabet[4],Lalphabet[24],Lalphabet[2],
     Lalphabet[2],Lalphabet[23],Lalphabet[2],Lalphabet[5],Lalphabet[0],Lalphabet[0],Lalphabet[4])

# Übersetzung der Zahlen in Buchstaben (gerundete Zahlen)

W F Z Y C E Y C C X C F A A E


In [50]:
def Entschluesselung(Eingabe, M):
    
    det = (M[0,0]*M[1,1]*M[2,2]+M[0,1]*M[1,2]*M[2,0]+M[0,2]*M[1,0]*M[2,1])-(M[0,2]*M[1,1]*M[2,0]+M[0,0]*M[1,2]*M[2,1]+M[0,1]*M[1,0]*M[2,2])
    # Determinante von Matrix
    
    Adj = np.array([[(M[2,2]*M[1,1]-M[1,2]*M[2,1]), -1*(M[0,1]*M[2,2]-M[0,2]*M[2,1]), (M[1,2]*M[0,1]-M[0,2]*M[1,1])],
                    [-1*(M[1,0]*M[2,2]-M[1,2]*M[2,0]), (M[0,0]*M[2,2]-M[0,2]*M[2,0]), -1*(M[0,0]*M[1,2]-M[0,2]*M[1,0])],
                    [(M[1,0]*M[2,1]-M[1,1]*M[2,0]), -1*(M[0,0]*M[2,1]-M[0,1]*M[2,0]), (M[0,0]*M[1,1]-M[0,1]*M[1,0])]])
    # adjunkte Matrix 
    
    Minvers = ((1/det) * Adj)                     # Formel für inverse Matrix
    
    Leingabe= list(Eingabe)
    
    L = []
    for i in range(len(Leingabe)):               # die Buchstaben der Eingabe werden durch den entsprechenden Index im Alphabet
        if Leingabe[i] in Lalphabet:             # ersetzt und zu neuer Liste hinzugefügt
            
            L.append(Lalphabet.index(Leingabe[i]))
            
    v = np.asarray(L)
    np.transpose(v)
    
    i = 0                                              # für die Entschlüsselung aller Buchstaben bzw. Indezes in v
    
    while i < len(v):                                  # Schleife wird durchlaufen, solange i < Anzahl Elemente in v
        
        v1 = np.array([[v[i]], [v[i+1]], [v[i+2]]])    # zu entschlüsselnde Vektoren mit drei nacheinander folgenden Elementen
                                                       # in v
        a = np.dot(Minvers, v1) % 26
        print(a)                                       # Ausgabe entschlüsselter Vektor
        
        i = i+3  
        
    return 0
    
            
    
    
    

In [51]:
print(Entschluesselung('WHKPXLMMFQXAGUQ', M))  # Ausgegebene Vektoren müssen in Buchstaben umgewandelt werden mit Lalphabet[i]

[[ 21.64741641]
 [  4.51671733]
 [ 25.46200608]]
[[ 23.94224924]
 [  1.55015198]
 [  4.38601824]]
[[ 23.83586626]
 [  1.82674772]
 [  1.93920973]]
[[ 22.75987842]
 [  2.02431611]
 [  4.76291793]]
[[  0.49240122]
 [ 25.51975684]
 [  4.18237082]]
0


In [53]:
print(Entschluesselung('WTMHET', M))  # die Entschlüsselung müsste 'YELLOW' ergeben

[[ 22.18237082]
 [  3.52583587]
 [  2.6231003 ]]
[[  1.51975684e-02]
 [  9.60486322e-01]
 [  2.56352584e+01]]
0


In [56]:
print(Lalphabet[23], Lalphabet[4], Lalphabet[3],Lalphabet[0],Lalphabet[1],Lalphabet[0])

X E D A B A
