In [1]:
import numpy as np

In [2]:
M = np.array([[3, 8, 2], [4, 6, 5], [19, 21, 4]])       # Verschlüsselungsmatrix M
print(M)

[[ 3  8  2]
 [ 4  6  5]
 [19 21  4]]


In [3]:
Eingabe = 'pferde'
Leingabe= list(Eingabe)                          # Umwandlung des Eingabestrings zu Liste
Alphabet = 'abcdefghijklmnopqrstuvwxyz'
Lalphabet= list(Alphabet)                        # Umwandlung des Alphabetstrings zu Liste

In [4]:
L = []
for i in range(len(Leingabe)):                   # die Buchstaben der Eingabe werden durch den entsprechenden Index im Alphabet
    if Leingabe[i] in Lalphabet:                 # ersetzt und zu neuer Liste hinzugefügt
        L.append(Lalphabet.index(Leingabe[i]))
    
print(L)

Lalphabet.index('u')



[15, 5, 4, 17, 3, 4]


20

In [5]:
v = np.asarray(L)                              # Vektor 1xn (n : Anzahl der Buchstaben ) mit den Listenelementen aus L
np.transpose(v)                                # v wird zu nx1 Vektor transponiert, nötig für Multiplikation mit M
v
l = np.array([[15],[5],[4]])                   # 3x1-Vektor mit den den Buchstaben entsprechenden Indezes (erste drei)
l2 = np.array([[17], [3], [4]])                # (folgende drei)

In [6]:
w = np.dot(M,l) % 26                           # w verschlüsselter Vektor, durch Multiplikation mit M modulo 26
print(w)
w2 = np.dot(M, l2) % 26
print(w2)

[[15]
 [ 6]
 [16]]
[[ 5]
 [ 2]
 [12]]


In [7]:
def Verschluesselung1(Text, Alphabet, Schluessel = M):   # erste Definition der Verschlüsselungsfunktion, Text kann nur mit je 
                                                        # drei Buchstaben eingegeben werden
    import numpy as np
    
    K = list(Text)                                      # Textstring wird zu Liste K gemacht, Alphabet-string zu Liste Lalphabet
    Lalphabet = list(Alphabet)
    
    L = []
    for i in range(len(K)):                             # den Buchstaben in K werden die entsprechenden Indezes in Lalphabet 
                                                        # zugeordnet und zur neuen Liste L hinzugefügt
        if K[i] in Lalphabet:
            L.append(Lalphabet.index(K[i]))
    
    v = np.asarray(L)                                   # aus L wird 1xn-Vektor v gemacht
    np.transpose(v)                                     # v transponiert, sodass v mit M multipliziert werden kann
    
    v1 = np.array([[v[0]], [v[1]], [v[2]]])             # v muss zu 3x1-Vektor verkürzt werden, v1 enthält erste drei Elemente
                                                        # von v 
    a = np.dot(M, v1) % 26                              # verschlüsselter Vektor aus Multiplikation von M und v1 modulo 26
                   
    return a                                            # Ausgabe verschlüsselter Vektor a
        
        

In [8]:
print(Verschluesselung1('pferd', Alphabet))              # Beispiel 1 für Verschluesselung, bei beliebig langer Eingabe werden 
                                                        # nur die ersten drei Buchstaben verschlüsselt ausgegeben

[[15]
 [ 6]
 [16]]


In [9]:
def Verschluesselung2(Text, Alphabet, Schluessel=M):    # Definition Verschlüsselungsfunktion, Text muss eine durch drei teilbare
                                                        # Anzahl an Buchstaben haben
    import numpy as np                                  # bis i = 0 wie Verschluesselung1
    
    K = list(Text)  
    Lalphabet = list(Alphabet)
    
    L = []
    for i in range(len(K)):
        
        if K[i] in Lalphabet:
            L.append(Lalphabet.index(K[i]))
    
    v = np.asarray(L)
    np.transpose(v)
    
    i = 0                                              # für die Verschlüsselung aller Buchstaben bzw. Indezes in v
    
    while i < len(v):                                  # Schleife wird durchlaufen, solange i < Anzahl Elemente in v
        
        v1 = np.array([[v[i]], [v[i+1]], [v[i+2]]])    # zu verschlüsselnde Vektoren mit drei nacheinander folgenden Elementen
                                                       # in v
        a = np.dot(M, v1) % 26
        print(a)                                       # Ausgabe verschlüsselter Vektor
        
        i = i+3                                        # Verschiebung i für die nächsten drei Stellen in v, ist i > len(v)
                                                       # wird die Schleife gestoppt, da keine Elemente mehr zu verschlüsseln sind
    return 0
        
    

In [10]:
print(Verschluesselung2('alle voegel sind schon da', Alphabet))  # Beispiel 2 Verschluesselung 2

[[ 6]
 [17]
 [15]]
[[0]
 [4]
 [1]]
[[16]
 [20]
 [10]]
[[11]
 [10]
 [21]]
[[21]
 [ 4]
 [18]]
[[12]
 [16]
 [ 7]]
[[11]
 [18]
 [24]]
0


In [25]:
print(Lalphabet[6],Lalphabet[17],Lalphabet[15],Lalphabet[0],Lalphabet[4],Lalphabet[1],Lalphabet[16],Lalphabet[20],
     Lalphabet[10],Lalphabet[11],Lalphabet[10],Lalphabet[21],Lalphabet[21],Lalphabet[4],Lalphabet[18],Lalphabet[12],
     Lalphabet[16],Lalphabet[7],Lalphabet[11],Lalphabet[18],Lalphabet[24])

# Beispiel 2

g r p a e b q u k l k v v e s m q h l s y


In [11]:
print(Verschluesselung2('das auto des praktikanten ist das groesste.', Alphabet))  # Beispiel 3 Veschluesselung2, kann keine 
                                                                                   # Sonderbuchstaben enthalten

[[19]
 [24]
 [25]]
[[16]
 [ 7]
 [ 2]]
[[22]
 [16]
 [ 7]]
[[ 0]
 [13]
 [23]]
[[14]
 [25]
 [ 0]]
[[ 0]
 [14]
 [24]]
[[17]
 [ 4]
 [12]]
[[ 9]
 [ 8]
 [19]]
[[ 3]
 [16]
 [ 8]]
[[ 6]
 [11]
 [16]]
[[ 6]
 [14]
 [ 6]]
[[ 6]
 [24]
 [ 3]]
0


In [24]:
print(Lalphabet[19],Lalphabet[24],Lalphabet[25],Lalphabet[16],Lalphabet[7],Lalphabet[2],Lalphabet[22],Lalphabet[16],
     Lalphabet[7],Lalphabet[0],Lalphabet[13],Lalphabet[23],Lalphabet[14],Lalphabet[25],Lalphabet[0],Lalphabet[0],
     Lalphabet[14],Lalphabet[24],Lalphabet[17],Lalphabet[4],Lalphabet[12],Lalphabet[9],Lalphabet[8],Lalphabet[19],
     Lalphabet[3],Lalphabet[16],Lalphabet[8],Lalphabet[6],Lalphabet[11],Lalphabet[16],Lalphabet[6],Lalphabet[14],
     Lalphabet[6],Lalphabet[6], Lalphabet[24],Lalphabet[3])

# Beispiel 3

t y z q h c w q h a n x o z a a o y r e m j i t d q i g l q g o g g y d


In [21]:
print(Verschluesselung2('yellow', Alphabet))  # Beispiel 4

[[22]
 [19]
 [12]]
[[ 7]
 [ 4]
 [19]]
0


In [23]:
print(Lalphabet[22], Lalphabet[19], Lalphabet[12], Lalphabet[7], Lalphabet[4], Lalphabet[19]) # Beispiel 4

w t m h e t
